### PR TITLE
fix(server): pymongo gridfs attribute error

### LINKED ISSUE #1117: bug: Attribute Error while starting application (Pymongo)
Description
----

The recently updated pymongo in #1057 breaks the system startup due to attribute error. 

Traceback: 
```
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 683, in spawn_worker
    worker.init_process()
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 136, in init_process
    self.load_wsgi()
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 148, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 377, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/srv/testflinger/app.py", line 22, in <module>
    app = create_flask_app(secrets_store=secrets_store)
  File "/srv/testflinger/src/testflinger/application.py", line 67, in create_flask_app
    setup_mongodb(tf_app)
  File "/srv/testflinger/src/testflinger/database.py", line 77, in setup_mongodb
    create_indexes()
  File "/srv/testflinger/src/testflinger/database.py", line 98, in create_indexes
    mongo.db.fs.chunks.create_index(
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/flask_pymongo/wrappers.py", line 81, in __getattr__
    attr = super().__getattr__(name)
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/pymongo/synchronous/collection.py", line 282, in __getattr__
    return self.__getitem__(name)
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/flask_pymongo/wrappers.py", line 90, in __getitem__
    db = self._Collection__database
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/flask_pymongo/wrappers.py", line 81, in __getattr__
    attr = super().__getattr__(name)
  File "/srv/testflinger/.venv/lib/python3.10/site-packages/pymongo/synchronous/collection.py", line 278, in __getattr__
    raise AttributeError(
AttributeError: Collection has no attribute '_Collection__database'. To access the fs._Collection__database collection, use database['fs._Collection__database'].
Collection has no attribute '_Collection__database'. To access the fs._Collection__database collection, use database['fs._Collection__database'].
```

Fix
----
Instead of `db.fs.files` it should be referred as `db["fs.files"]`. Same pattern for `fs.chunks`

### PR DESCRIPTION
**Pull request by rene-oromtz**
## Description
This fixes a bug introduced in #1057 by pymongo<4.17. 

## Resolved issues
Resolves #1117

## Documentation
NA

## Web service API changes
NA

## Tests
Added unit tests as the GridFS was completely missing. For testing this fix, the integration test is the actually relevant as currently, integration tests are failing as the application is unable to start. Unforntunately, the integration tests will fail until after this is merged as the integration tests uses the container image from `main`

### CODE REVIEW

**Review by ajzobro — APPROVED** [review]
LGTM, happy to see more tests getting added in general
